package lt.vu.usecases.mybatis.model;

public class Club {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.NAME
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.NAME
     *
     * @return the value of PUBLIC.COURSE.NAME
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.NAME
     *
     * @param name the value for PUBLIC.COURSE.NAME
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }
}